name: 'Search Index Action'
author: "Yoseph Tamene"
description: 'Creates a search index using the xmls'
inputs:
  xml-directory:
    description: 'The directory where the xml files are located'
    default: './'
  index-directory:
    description: 'The directory where the output index.json file is placed'
    default: './'
outputs:
  index: 
    description: 'The search index to be saved in index.json'
  time: # id of output
    description: 'The time the action was run'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'search'
  color: 'blue